#!/bin/bash

# ----------  ---------- #

if [ "$1" == "purge" ]; then

	cd /																					# This was created in postinst
	rm api > /dev/null 2>&1 || true

	rm -r /var/lib/spaceify > /dev/null 2>&1 || true

fi

# ----------  ---------- #
if [ -e /usr/share/debconf/confmodule ]; then

	. /usr/share/debconf/confmodule
	db_purge

fi

if [ -f /etc/NetworkManager/dnsmasq.d/spaceify.conf ]; then

	rm /etc/NetworkManager/dnsmasq.d/spaceify.conf
	service network-manager restart

fi

if [ -f /etc/dnsmasq.d/spaceify.conf ]; then

	rm /etc/dnsmasq.d/spaceify.conf
	service dnsmasq restart

fi

#The debhelper-generated stuff should appear in place of the following comment

#DEBHELPER#

systemctl restart docker

#
